services:
  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fedora
  graphdb:
    build:
      context: ./graphdb
      dockerfile: Dockerfile
    volumes:
      - graphdb-data:/data
    ports:
      - 7200:7200
  # activemq is already part of fcrepo?
  # activemq:
  #   build:
  #     context: ./activemq
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8161:8161
  #     - 61616:61616
  fcrepo:
    build:
      context: ./fcrepo
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      CATALINA_OPTS: "-Dfcrepo.jms.baseUrl=http://fcrepo:6161"
    volumes:
      - fcrepo-data:/data
      - ./fcrepo-config:/opt/fcrepo/config
      - archive-data:/mnt/vfs1/archive/archive-data
  php:
    image: php:8.3-fpm
    container_name: php-fpm
    volumes:
      - ./drupal-content:/var/www/html
  drupal:
    environment:
      - POSTGRES_PASSWORD=fedora
      - DRUPAL_DB_HOST=postgres
      - DRUPAL_DB_NAME=drupal
      - DRUPAL_DB_USER=drupal
      - DRUPAL_DB_PASSWORD=drupalpassword
      - DRUPAL_DB_DRIVER=pgsql
    volumes:
      - ./drupal-content:/var/www/html
    build:
      context: ./drupal
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - php
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./drupal-content:/var/www/html
    depends_on:
      - php
  solr:
    build:
      context: ./solr
      dockerfile: Dockerfile
    ports:
      - 8983:8983
    volumes:
      - solr-data:/data:rw
      - type: volume
        source: drupal-solr-config
        target: /opt/solr/server/solr/default
        volume:
          nocopy: true
  fits:
    image: islandora/fits:3.4.2
    ports:
      - 8081:8080
    volumes:
      - archive-data:/mnt/vfs1/archive/archive-data
  cantaloupe:
    image: islandora/cantaloupe:3.4
    ports:
      - 8182:8182
    volumes:
      - archive-data:/mnt/vfs1/archive/archive-data
      - cantaloupe-data:/data:rw
  portainer:
    build:
      context: ./portainer
      dockerfile: Dockerfile
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
volumes:
  drupal_sites:
  db_data:
  graphdb-data:
  drupal-solr-config:
  solr-data:
  archive-data:
  cantaloupe-data:
  fcrepo-data:
