services:
  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fedora
  # graphdb:
  #   build:
  #     context: ./graphdb
  #     dockerfile: Dockerfile
  #   volumes:
  #     - graphdb-data:/data
  #   ports:
  #     - 7200:7200
  # activemq is already part of fcrepo?
  # activemq:
  #   build:
  #     context: ./activemq
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8161:8161
  #     - 61616:61616
  # fcrepo:
  #   build:
  #     context: ./fcrepo
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   environment:
  #     CATALINA_OPTS: "-Dfcrepo.jms.baseUrl=http://fcrepo:6161"
  #   volumes:
  #     - fcrepo-data:/data
  #     - ./fcrepo-config:/opt/fcrepo/config
  #     - archive-data:/mnt/vfs1/archive/archive-data
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./drupal-content:/var/www/html
    depends_on:
      - php
  php:
    environment:
      - POSTGRES_PASSWORD=fedora
      - DRUPAL_DB_HOST=postgres
      - DB_POSTGRES_HOST=postgres
      - DB_POSTGRES_PORT=5432
      - DRUPAL_DB_NAME=drupal
      - DRUPAL_DB_USER=drupal
      - DRUPAL_DB_PASSWORD=drupalpassword
      - DRUPAL_DB_DRIVER=pgsql
      - DRUPAL_DEFAULT_ACCOUNT_EMAIL=webmaster@localhost.com \
      - DRUPAL_DEFAULT_ACCOUNT_NAME=admin \
      - DRUPAL_DEFAULT_ACCOUNT_PASSWORD=password \
      - DRUPAL_DEFAULT_BROKER_HOST=activemq \
      - DRUPAL_DEFAULT_BROKER_PORT=61613 \
      - DRUPAL_DEFAULT_BROKER_URL=tcp://activemq:61613 \
      - DRUPAL_DEFAULT_BROKER_WEB_ADMIN_PASSWORD=password \
      - DRUPAL_DEFAULT_BROKER_WEB_ADMIN_USER=admin \
      - DRUPAL_DEFAULT_BROKER_WEB_PORT=8161 \
      - DRUPAL_DEFAULT_CANTALOUPE_URL=https://islandora.traefik.me/cantaloupe/iiif/2 \
      - DRUPAL_DEFAULT_CONFIGDIR=/var/www/drupal/config/sync \
      - DRUPAL_DEFAULT_DB_NAME=drupal \
      - DRUPAL_DEFAULT_DB_PASSWORD=drupalpassword \
      - DRUPAL_DEFAULT_DB_USER=drupal \
      - DRUPAL_DEFAULT_EMAIL=webmaster@localhost.com \
      - DRUPAL_DEFAULT_FCREPO_HOST=islandora.traefik.me \
      - DRUPAL_DEFAULT_FCREPO_PORT=8081 \
      - DRUPAL_DEFAULT_FITS_HOST=fits \
      - DRUPAL_DEFAULT_FITS_PORT=8080 \
      - DRUPAL_DEFAULT_INSTALL_EXISTING_CONFIG=false \
      - DRUPAL_DEFAULT_INSTALL=true \
      - DRUPAL_DEFAULT_LOCALE=en \
      - DRUPAL_DEFAULT_MATOMO_URL_HTTP=http://islandora.traefik.me/matomo/ \
      - DRUPAL_DEFAULT_MATOMO_URL_HTTPS=https://islandora.traefik.me/matomo/ \
      - DRUPAL_DEFAULT_NAME=Default \
      - DRUPAL_DEFAULT_PROFILE=standard \
      - DRUPAL_DEFAULT_SALT=9PPaL0CxZAIcq0l9wxgDGlCZrp7JdT_x7v9gVzpdbUjMt1PqDz3uD0Zy-i16DuJ1-Htuq5hqeg \
      #- DRUPAL_DEFAULT_SITE_URL=https://islandora.traefik.me \
      - DRUPAL_DEFAULT_SOLR_CORE=ISLANDORA \
      - DRUPAL_DEFAULT_SOLR_HOST=solr \
      - DRUPAL_DEFAULT_SOLR_PORT=8983 \
      #- DRUPAL_DEFAULT_SUBDIR=default \
      - DRUPAL_DEFAULT_TRIPLESTORE_HOST=blazegraph \
      - DRUPAL_DEFAULT_TRIPLESTORE_NAMESPACE=islandora \
      - DRUPAL_DEFAULT_TRIPLESTORE_PORT=8080 \
      #- DRUPAL_ENABLE_HTTPS=true \
      #- DRUPAL_REVERSE_PROXY_IPS= \
      #- DRUPAL_SITES=DEFAULT
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        - POSTGRES_PASSWORD=fedora
        - DRUPAL_DB_HOST=postgres
        - DB_POSTGRES_HOST=postgres
        - DB_POSTGRES_PORT=5432
        - DRUPAL_DB_NAME=drupal
        - DRUPAL_DB_USER=drupal
        - DRUPAL_DB_PASSWORD=drupalpassword
        - DRUPAL_DB_DRIVER=pgsql
        - DRUPAL_DEFAULT_ACCOUNT_EMAIL=webmaster@localhost.com \
        - DRUPAL_DEFAULT_ACCOUNT_NAME=admin \
        - DRUPAL_DEFAULT_ACCOUNT_PASSWORD=password \
        - DRUPAL_DEFAULT_BROKER_HOST=activemq \
        - DRUPAL_DEFAULT_BROKER_PORT=61613 \
        - DRUPAL_DEFAULT_BROKER_URL=tcp://activemq:61613 \
        - DRUPAL_DEFAULT_BROKER_WEB_ADMIN_PASSWORD=password \
        - DRUPAL_DEFAULT_BROKER_WEB_ADMIN_USER=admin \
        - DRUPAL_DEFAULT_BROKER_WEB_PORT=8161 \
        - DRUPAL_DEFAULT_CANTALOUPE_URL=https://islandora.traefik.me/cantaloupe/iiif/2 \
        - DRUPAL_DEFAULT_CONFIGDIR=/var/www/drupal/config/sync \
        - DRUPAL_DEFAULT_DB_NAME=drupal \
        - DRUPAL_DEFAULT_DB_PASSWORD=drupalpassword \
        - DRUPAL_DEFAULT_DB_USER=drupal \
        - DRUPAL_DEFAULT_EMAIL=webmaster@localhost.com \
        - DRUPAL_DEFAULT_FCREPO_HOST=islandora.traefik.me \
        - DRUPAL_DEFAULT_FCREPO_PORT=8081 \
        - DRUPAL_DEFAULT_FITS_HOST=fits \
        - DRUPAL_DEFAULT_FITS_PORT=8080 \
        - DRUPAL_DEFAULT_INSTALL_EXISTING_CONFIG=false \
        - DRUPAL_DEFAULT_INSTALL=true \
        - DRUPAL_DEFAULT_LOCALE=en \
        - DRUPAL_DEFAULT_MATOMO_URL_HTTP=http://islandora.traefik.me/matomo/ \
        - DRUPAL_DEFAULT_MATOMO_URL_HTTPS=https://islandora.traefik.me/matomo/ \
        - DRUPAL_DEFAULT_NAME=Default \
        - DRUPAL_DEFAULT_PROFILE=standard \
        - DRUPAL_DEFAULT_SALT=9PPaL0CxZAIcq0l9wxgDGlCZrp7JdT_x7v9gVzpdbUjMt1PqDz3uD0Zy-i16DuJ1-Htuq5hqeg \
        #- DRUPAL_DEFAULT_SITE_URL=https://islandora.traefik.me \
        - DRUPAL_DEFAULT_SOLR_CORE=ISLANDORA \
        - DRUPAL_DEFAULT_SOLR_HOST=solr \
        - DRUPAL_DEFAULT_SOLR_PORT=8983 \
        #- DRUPAL_DEFAULT_SUBDIR=default \
        - DRUPAL_DEFAULT_TRIPLESTORE_HOST=blazegraph \
        - DRUPAL_DEFAULT_TRIPLESTORE_NAMESPACE=islandora \
        - DRUPAL_DEFAULT_TRIPLESTORE_PORT=8080 \

    volumes:
      - ./drupal-content:/var/www/html
    entrypoint: ["sh", "/usr/local/bin/install-drupal.sh"]
  # drupal:
  #   environment:
  #     - POSTGRES_PASSWORD=fedora
  #     - DRUPAL_DB_HOST=postgres
  #     - DRUPAL_DB_NAME=drupal
  #     - DRUPAL_DB_USER=drupal
  #     - DRUPAL_DB_PASSWORD=drupalpassword
  #     - DRUPAL_DB_DRIVER=pgsql
  #   volumes:
  #     - ./drupal-content:/opt/drupal
  #   build:
  #     context: ./drupal
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres
  #     - php
  # solr:
  #   build:
  #     context: ./solr
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8983:8983
  #   volumes:
  #     - solr-data:/data:rw
  #     - type: volume
  #       source: drupal-solr-config
  #       target: /opt/solr/server/solr/default
  #       volume:
  #         nocopy: true
  # fits:
  #   image: islandora/fits:3.4.2
  #   ports:
  #     - 8081:8080
  #   volumes:
  #     - archive-data:/mnt/vfs1/archive/archive-data
  # cantaloupe:
  #   image: islandora/cantaloupe:3.4
  #   ports:
  #     - 8182:8182
  #   volumes:
  #     - archive-data:/mnt/vfs1/archive/archive-data
  #     - cantaloupe-data:/data:rw
  # portainer:
  #   build:
  #     context: ./portainer
  #     dockerfile: Dockerfile
  #   ports:
  #     - 9443:9443
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./portainer_data:/data
volumes:
  drupal_sites:
  db_data:
  graphdb-data:
  drupal-solr-config:
  solr-data:
  archive-data:
  cantaloupe-data:
  fcrepo-data:
